# Generated by Django 3.1.7 on 2022-06-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='channel_name',
        ),
    ]
