# Generated by Django 3.1.7 on 2022-06-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_auto_20220609_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='channelname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channel.channel'),
        ),
    ]
