# Generated by Django 3.1.7 on 2022-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_auto_20220609_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='soil',
            field=models.CharField(default=4, max_length=120),
            preserve_default=False,
        ),
    ]
