# Generated by Django 4.0.4 on 2022-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rtData',
            new_name='DataRT',
        ),
        migrations.AlterModelTable(
            name='datart',
            table='DataRT',
        ),
    ]
