# Generated by Django 4.0.4 on 2022-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRT', '0003_datart_valother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datart',
            name='valOther',
        ),
    ]
