# Generated by Django 3.1.7 on 2022-06-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRT', '0004_remove_datart_valother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
