# Generated by Django 3.2.7 on 2021-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_y', models.CharField(max_length=100)),
                ('num_x', models.IntegerField()),
            ],
            options={
                'db_table': 'charts',
            },
        ),
    ]
